.extern _ZN5Riscv13handleConsoleEv

.align 4
.global _ZN5Riscv11consoleTrapEv
.type _ZN5Riscv11consoleTrapEv, @function
_ZN5Riscv11consoleTrapEv:
    # push all registers to stack
    addi sp, sp, -256
    .irp index, 0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31 //a0-10
    sd x\index, \index * 8(sp)
    .endr

    call _ZN5Riscv13handleConsoleEv

    # pop all registers from stack
   .irp index, 0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31 //a0-10
    ld x\index, \index * 8(sp)
   .endr
    addi sp, sp, 256


    sret
